// Generated by purs bundle 0.12.5
var PS = {};
(function(exports) {
  "use strict";
  var sketch =require("sketch/dom");
  var ui =require("sketch/ui");

  exports.showMessage = function(text) {
    return function() {
      ui.message(text);
      return {};  
    };
  };
})(PS["Lib.Sketch"] = PS["Lib.Sketch"] || {});
(function($PS) {
  // Generated by purs version 0.12.5
  "use strict";
  $PS["Lib.Sketch"] = $PS["Lib.Sketch"] || {};
  var exports = $PS["Lib.Sketch"];
  var $foreign = $PS["Lib.Sketch"];
  exports["showMessage"] = $foreign.showMessage;
})(PS);
(function($PS) {
  // Generated by purs version 0.12.5
  "use strict";
  $PS["Main"] = $PS["Main"] || {};
  var exports = $PS["Main"];
  var Lib_Sketch = $PS["Lib.Sketch"];                
  var myCommand = Lib_Sketch.showMessage("It's alive \ud83d\ude4c");
  exports["myCommand"] = myCommand;
})(PS);
module.exports = PS;
