// Generated by purs bundle 0.12.5
var PS = {};
(function (exports) {
    "use strict";
    var ui = require("sketch/ui");

    exports["message"] = function (text) {
        return function () {
            ui.message(text);
            return {};
        };
    };
})(PS["Sketch.UI"] = PS["Sketch.UI"] || {});
(function ($PS) {
    // Generated by purs version 0.12.5
    "use strict";
    $PS["Sketch.UI"] = $PS["Sketch.UI"] || {};
    var exports = $PS["Sketch.UI"];
    var $foreign = $PS["Sketch.UI"];
    exports["message"] = $foreign.message;
})(PS);
(function ($PS) {
    // Generated by purs version 0.12.5
    "use strict";
    $PS["Main"] = $PS["Main"] || {};
    var exports = $PS["Main"];
    var Sketch_UI = $PS["Sketch.UI"];
    var myCommand = Sketch_UI.message("It's alive \ud83d\ude4c");
    exports["myCommand"] = myCommand;
})(PS);
module.exports = PS;
